build:
  image: golang:$$GO_VERSION
  commands:
   - apk --no-cache --quiet add curl git cvs gcc musl-dev make cmake libssh2-dev openssl-dev
   - export PKG_CONFIG_PATH="/usr/lib/pkgconfig/:/usr/local/lib/pkgconfig/"
   - go get
   - go build
   - go test

matrix:
  GO_VERSION:
  - 1.13-alpine
