FROM python:3.7-alpine

MAINTAINER x0rzkov@protonmail.com

RUN apk add --no-cache nano bash git ca-certificates cython openblas-dev musl-dev python3-dev libffi-dev gcc g++

COPY requirements.txt /opt/app/requirements.txt
WORKDIR /opt/app/

RUN pip3 install -r requirements.txt

COPY twitter-graph.py /opt/app/twitter-graph.py


CMD ["/bin/bash"]
